{% set name = "dist-meta" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/repo-helper/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0e2337a7c4db6c8b12ce626bb19812f5fd0b793838b21fbac3b5dfd074394255

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-requirements-txt
  run:
    - python
    - domdf-python-tools >=3.1.0
    - handy-archives >=0.1.0
    - packaging >=20.9
  run_constrained:
    # requires-python = ">=3.6.1"
    - python >=3.6.1

# ModuleNotFoundError: No module named 'first'
{% set ignore_tests = " --ignore=tests/test_distributions.py" %}
# ModuleNotFoundError: No module named 'apeye'
{% set ignore_tests = ignore_tests + " --ignore=tests/test_metadata_top_packages.py" %}

test:
  source_files:
    - tests
  imports:
    - dist_meta
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ ignore_tests }} tests
  requires:
    - pip
    - pytest
    - coincidence
    - shippinglabel
    - apeye-core

about:
  home: https://github.com/repo-helper/dist-meta
  summary: Parse and create Python distribution metadata.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Parse and create Python distribution metadata.
  doc_url: https://dist-meta.readthedocs.io
  dev_url: https://github.com/repo-helper/dist-meta

extra:
  recipe-maintainers:
    - domdfcoding
